= Hands-On Module: Hello Redis
:source-highlighter: coderay

== Overview 

This directory contains files to use for the first hands-on exercise, building the classic 
Hello World with a Redis twist.  In this session, you will create a Hello Redis program
which connects to Redis, writes a message to the database, reads that message back, then
displays the message to the end user.  After that you will modify the program to add a 
counter to track the number of times the program executes. 

The file `HelloRedisApplication.java` is a skeleton program to get you started.  It provides and explains
the basic code needed to set up a connection to Redis.  If you get stuck `HelloRedisSolution.java`
implements a solution to the exercise.  Feel free to study it or get help from the training staff.

Although this is a hands-on exercise, we want to encourage you to use this time to ask 
questions of the training staff as well.

== Part One

. Prior to modifying `HelloRedisApplication.java`, run the app and see what happens:
[source,shell]
----
mvnw spring-boot:run
----
 
. Add connection parameters for your Redis database and verify you can connect to it:  
[source,shell]
----
mvnw spring-boot:run -Dspring.redis.host=<host> -Dspring.redis.port=<port>
----
 
. Add code to the program to store a Hello World message in Redis
. Modify the code that prints the message to read the message from Redis instead of a constant string
. Run the app again using your Redis connection parameters

== Part Two

. Add code to `HelloRedisApplication.java` to track how often the program runs
. Uncomment the code to print the run count message and modify to use the value from Redis

.Further Activities
- What happens if you and a classmate run your programs against the same database concurrently? Do you see any problems?
- Compare your solution with ours.  What differences, if any, do you notice? Are they meaningful?

== Part Three (Optional)
If you are familiar with other languages, try to build this same exercise in the language of your choice.