= Hands-On Session: RedisJSON

== Overview

This exercise demonstrates using both a module and specifically, RedisJSON. 

You will learn how to execute non-standard Redis commands directly from Java and learn a few commands to manipulate JSON directly from within Redis.

This directory contains files to use for the exercise.  The `RedisJSONApplication` class provides a skeleton to
help you get started. If you get stuck, files in the `solution` package implement our solution to 
the exercise.  Feel free to study it or ask questions of the training staff.

Although this is a hands-on exercise, we want to encourage you to use this time to ask 
questions of the training staff as well.

== Part One: Review RedisJSON Documentation

Please review the following documentation on redis.io to get started:

- https://oss.redislabs.com/redisjson/commands/[RedisJSON API]
- https://github.com/RedisJSON/JReJSON[JReJSON Java client]

== Part Two: Update JSON from within Redis

. Prior to modifying `RedisJSON.java`, run the program and see what happens.
. Update the file with your connection information.
. Write code to set the `last` field in the `name` object of the Key to "Sanfilippo".
. Write code to append "Sicily" to the `location` array in the Key.
. Write code to increment `age` in the Key from 40 to 41.

### Further Activities

1. Write code to delete the the `first` field from the `last` object using `JSON.DEL`
2. Write code to remove the 'Campobello di Licata' from the `location` array.

