= Hands-On Session: Streams
:source-highlighter: coderay

== Overview

This exercise demonstrates the Redis Streams data structure by building a simulation of messages
being sent from producers to consumers in response to events happening on a website.  For this
session, you will need to review the Redis Streams commands, create a publisher that sends messages
via Redis, then create a set of consumers to receive and process the messages.

This directory contains two modules to use for the exercise:

- The `streams-producer` module contains the message producer application
- The `streams-consumer` module contains the message consumer application

We have added code to manage multiple producers and consumers running locally 
and to help create simulated messages.  If you get stuck, files ending with `Solution.java` implement our solution to 
the exercise.  Feel free to study it or ask questions of the training staff.

Although this is a hands-on exercise, we want to encourage you to use this time to ask 
questions of the training staff as well.

== Part One: Review Streams Documentation

Please review the following documentation on Redis Streams to get started:

- https://redis.io/topics/streams-intro[Introduction to Redis Streams]
- https://www.javacodegeeks.com/2018/05/a-first-look-at-redis-streams-and-how-to-use-them-with-java.html[A first look at Redis Streams and how to use them with Java] 

== Part Two: Create a Producer

. Modify the `streams-producer` code to send messages via Redis in a loop
. Run the producer using your connection information

[source,shell]
----
mvnw spring-boot:run -Dspring.redis.host=<host> -Dspring.redis.port=<port>
----

== Part Three: Create a Consumer

. Open the `streams-consumer` module
. Add code to read a message from the appropriate stream
. Run a single consumer and look for messages received.
. Run a second consumer and watch the distribution of messages between the two application instances.

== Part Four: Using Consumer Groups

. Modify the `streams-consumer` code to listen for messages in a consumer group.
. Start two consumers and look at the message distribution. What's different? 

TIP: Read the section on consumer groups at the end of this article: https://www.javacodegeeks.com/2018/05/a-first-look-at-redis-streams-and-how-to-use-them-with-java.html[A first look at Redis Streams and how to use them with Java]

.Further Activities
- Why do you think we have separate producer and consumer applications?
- How can you test this code without the producer code?
